---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - repo.yaml
  - release.yaml

configurations:
  - configuration.yaml

configMapGenerator:
  - name: ops-properties
    namespace: default
    envs: [ environment.properties ]

vars:
  - name: AWS_ACCOUNT
    objref: { kind: ConfigMap, name: ops-properties, apiVersion: v1 }
    fieldref: { fieldpath: data.AWS_ACCOUNT }
  - name: CLUSTER_NAME
    objref: { kind: ConfigMap, name: ops-properties, apiVersion: v1 }
    fieldref: { fieldpath: data.CLUSTER_NAME }
  - name: TARGET_NAMESPACE
    objref: { kind: ConfigMap, name: ops-properties, apiVersion: v1 }
    fieldref: { fieldpath: data.TARGET_NAMESPACE }