apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: frontend
  namespace: flux-system
resources:
  - ../../base/frontend/quasar-app.yaml

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: flux-system
spec:
  chart:
    spec:
      chart: podinfo
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: podinfo
      version: '>4.0.0'
  interval: 10m0s
