apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: quasar-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: your-domain.com  # Replace with your actual domain
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: quasar-service  # Replace with the name of your Quasar service
                port:
                  number: 9000
