---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: quasar-app
  namespace: default
spec:
  interval: 1m0s
  releaseName: quasar-project
  chart:
    spec:
      chart: quasar-project
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: ghcr-oci
  #      version: '>4.0.0'
  values:
    replicaCount: 2
    service:
      type: LoadBalancer
      port: 9000
    image:
      repository: ghcr.io/maggnus/quasar-project
      imagePullPolicy: Always
      tag: 0.2.3
      #      ports:
      #        - name: app
      #          containerPort: 9000
      #          protocol: TCP
      imagePullSecrets:
        - name: ghcr-secret
      #        - name: ghcr-secret
      #          namespace: flux-system
      securityContext:
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 1000


#image:
#  repository: nginx
#  pullPolicy: IfNotPresent
#  # Overrides the image tag whose default is the chart appVersion.
#  tag: ""
#
#imagePullSecrets: []
#nameOverride: ""
#fullnameOverride: ""