---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: quasar-app
  namespace: flux-system
spec:
  chart:
    spec:
      chart: quasar-project
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: ghcr-oci
  #      version: '>4.0.0'
  interval: 1m0s
