---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: quasar-project
  namespace: default
spec:
  interval: 1m0s
  releaseName: quasar-project
  chart:
    spec:
      chart: quasar-project
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        #        namespace: dev
        name: ghcr-oci
  values:
    replicaCount: 2
    service:
      type: ClusterIP
      port: 80
    image:
      repository: ghcr.io/maggnus/quasar-project
      imagePullPolicy: Always
      tag: latest
    imagePullSecrets:
      - name: ghcr-secret
    securityContext:
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
