---
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-auth
  namespace: flux-system
stringData:
  .dockerconfigjson: '{"auths":{"ghcr.io":{"username":"flux","password":"test","auth":"Zmx1eDp0ZXN0"}}}'
type: kubernetes.io/dockerconfigjson

---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: github
  namespace: flux-system
spec:
  interval: 10m
  type: oci
  url: oci://ghcr.io/maggnus/charts/
  secretRef:
    name: ghcr-auth

#---
#apiVersion: source.toolkit.fluxcd.io/v1beta2
#kind: OCIRepository
#metadata:
#  name: quasar-app
#  namespace: flux-system
#spec:
#  url: oci://ghcr.io/maggnus/charts/quasar-project
#  ref:
#    tag: latest
#  interval: 1m0s
