---
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-auth
  namespace: flux-system
stringData:
  username: "maggnus"
  password: "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"

---
apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  namespace: flux-system
stringData:
  .dockerconfigjson: '{"auths":{"ghcr.io":{"username":"maggnus","password":"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","auth":"bWFnZ251czpnaHBfQjNOaFNESW1IRVV5WGNOczBIcXVUQVpGVFgwZkhWMmNGTGxZ"}}}'
type: kubernetes.io/dockerconfigjson


---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ghcr-oci
  namespace: flux-system
spec:
  interval: 1m
  type: oci
  url: oci://ghcr.io/maggnus/charts/
  secretRef:
    name: ghcr-auth
