#apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
#kind: Kustomization
#metadata:
#  name: 01-quasar-dev
#  namespace: flux-system
#spec:
#  interval: 1m0s
#  sourceRef:
#    kind: GitRepository
#    name: flux-system
#    namespace: flux-system
#  path: ./apps/staging
#  prune: true
#  #validation: client