---
apiVersion: v1
kind: Secret
metadata:
  name: default
  namespace: flux-system
stringData:
  .dockerconfigjson: '{"auths":{"ghcr.io":{"username":"maggnus","password":"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","auth":"bWFnZ251czpnaHBfQjNOaFNESW1IRVV5WGNOczBIcXVUQVpGVFgwZkhWMmNGTGxZ"}}}'
type: kubernetes.io/dockerconfigjson

