---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ghcr-oci
  namespace: default
spec:
  interval: 1m
  type: oci
  url: oci://ghcr.io/maggnus/charts/
  secretRef:
    name: ghcr-oci
