---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: flux-system
spec:
  chart:
    spec:
      chart: metrics-server
      sourceRef:
        kind: HelmRepository
        name: metrics-server
  interval: 5m
  timeout: 10m
  releaseName: metrics-server
  values:
    tolerations:
      - key: node/public
        operator: "Exists"
        effect: "NoSchedule"
      - key: dedicated
        operator: "Exists"
        effect: "NoSchedule"