name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - '.github/**'
      - 'app/**'
      - 'helm/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - '.github/**'
      - 'app/**'
      - 'helm/**'
  release:
    types:
      - created

env:
  REGISTRY: ghcr.io
  PROJECT_NAME: ${{ github.event.repository.name }}
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'

      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v0
        with:
          useConfigFile: true

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./app/quasar-app
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest,${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.GitVersion_SemVer }}
          labels: ${{ env.DOCKER_METADATA_OUTPUT_LABELS }}

      - name: Build and push Helm chart to OCI registry (Github)
        uses: appany/helm-oci-chart-releaser@v0.3.0
        with:
          name: ${{ env.PROJECT_NAME }}
          tag: ${{ env.GitVersion_SemVer }}
          path: ./helm
          registry: ${{ env.REGISTRY }}
          repository: maggnus/charts
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
          update_dependencies: 'true' # Defaults to false
